#+title:Doom-Emacs install
#+PROPERTY: header-args :tangle install
#+DESCRIPTION: Installation script for doom-emacs on Ubuntu
#+AUTO_TANGLE: t
#+AUTHOR: Jonas Ingemarsson
#+STARTUP: showeverything

* TABLE OF CONTENTS :toc:
- [[#about][ABOUT]]
- [[#before-running-the-install][BEFORE RUNNING THE INSTALL]]
- [[#installation][INSTALLATION]]
  - [[#adding-repository][ADDING REPOSITORY]]
  - [[#install-emacs--doom-emacs][INSTALL EMACS & DOOM-EMACS]]
- [[#post-configuration][POST CONFIGURATION]]
  - [[#adding-emacs-daemon-to-autostart][ADDING EMACS DAEMON TO AUTOSTART]]
  - [[#create-alias][CREATE ALIAS]]
  - [[#desktop-icon][DESKTOP ICON]]

* ABOUT
This is instructions on how to install Doom-Emacs on your Ubuntu 20.04+ system.
To install, either copy paste the commands stated in the guide, or run the installation script.
/You might need to make the install script executable by running the below command/

*chmod +x install*

* BEFORE RUNNING THE INSTALL
Make sure to remove any conflicting emacs onto your system

#+begin_src shell
#!/bin/bash
sudo apt remove --autoremove emacs emacs-common
#+end_src

* INSTALLATION
Do not skip any of the moments when installing

** ADDING REPOSITORY

#+begin_src shell
sudo add-apt-repository ppa:kelleyk/emacs
#+end_src

Perform a system update before installing Emacs

#+begin_src shell
sudo apt update
#+end_src

** INSTALL EMACS & DOOM-EMACS
This guide uses Emacs 28. If using this guide in future, a later version might be present. Also, Doom-Emacs will be installed in this part.

#+begin_src shell
sudo apt install emacs28
git clone https://github.com/hlissner/doom-emacs ~/.emacs.d
#+end_src

*** ADDING EMACS TO YOUR PATH
Before continuing the installation you should add Emacs to your PATH.

#+begin_src shell
echo 'export PATH="$HOME/.emacs.d/bin:$PATH" >> ~/.bashrc'
source ~/.bashrc
#+end_src

*** INSTALL DOOM-EMACS

#+begin_src shell
~/.emacs.d/bin/doom install
#+end_src

* POST CONFIGURATION
This part is optional but will enhance the experience.

** ADDING EMACS DAEMON TO AUTOSTART
To speed up the launch of Doom-Emacs, I suggest to add the daemon (server) to autostart. This can be done in /Startup Applications/ in Ubuntu. Add a new one with the following command:

*/usr/bin/emacs --daemon*

** CREATE ALIAS
By creating an alias to launch Doom-Emacs you shorten the time and make it easier to launch. This can be done by adding the following alias to your .bashrc.

alias emacs="emacsclient -c -a 'emacs'"

After adding the alias, make sure to run the command *source ~/.bashrc* to apply.

** DESKTOP ICON
To create a Desktop Icon for Doom-Emacs, the easiest way is to copy the all ready created Emacs desktop and modify that. Do that by running the below command.

Move to applications directory
*cd /usr/share/applications*

Make a copy of Emacs desktop file
*cp emacs.desktop emacsclient.desktop*

Open *emacsclient.desktop* and change the *Name* to *emacsclient (GUI)* and the *Exec* to /usr/bin/emacsclient -c -a 'emacs'
